package restore

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"testing"

	"github.com/aarohkandy/auros-installer/internal/manifest"
)

// buildArchive writes a real archive: real files at their stored paths and a
// real manifest over them.
//
// It goes through manifest.Add and manifest.Bytes rather than writing the TSV
// by hand, because a hand-written manifest is a test that agrees with the test
// author instead of with the program. The only hand-written manifests in this
// package are the deliberately broken ones.
func buildArchive(t *testing.T, root string, files map[string]string) *Archive {
	t.Helper()
	m := manifest.New()
	taken := map[string]bool{}
	for logical, content := range files {
		clean, err := manifest.CleanRel(logical)
		if err != nil {
			t.Fatalf("test fixture path %q is not usable: %v", logical, err)
		}
		stored, _ := manifest.Sanitize(clean)
		stored = manifest.DeCollide(stored, taken)
		taken[manifest.FoldKey(stored)] = true

		full := filepath.Join(root, filepath.FromSlash(stored))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		sum := sha256.Sum256([]byte(content))
		if err := m.Add(manifest.Entry{
			Path:            clean,
			Stored:          stored,
			Size:            int64(len(content)),
			ModTimeUnixNano: 1600000000000000000,
			SHA256:          hex.EncodeToString(sum[:]),
		}); err != nil {
			t.Fatalf("adding %q: %v", logical, err)
		}
	}
	writeManifest(t, root, m.Bytes())
	return loadForTest(t, root)
}

func writeManifest(t *testing.T, root string, body []byte) {
	t.Helper()
	dir := filepath.Join(root, manifest.MetaDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, manifest.FileName), body, 0o644); err != nil {
		t.Fatal(err)
	}
}

func loadForTest(t *testing.T, root string) *Archive {
	t.Helper()
	f := &Finder{Explicit: root}
	found, err := f.Find()
	if err != nil {
		t.Fatalf("loading the archive just written at %s: %v", root, err)
	}
	return found[0]
}

// newHome makes a home directory with an explicit user-dirs.dirs, so no test
// depends on the XDG configuration of whatever machine it runs on.
func newHome(t *testing.T) (home string, l *Layout) {
	t.Helper()
	home = t.TempDir()
	cfg := filepath.Join(home, ".config")
	if err := os.MkdirAll(cfg, 0o755); err != nil {
		t.Fatal(err)
	}
	body := `# generated by the test
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
`
	if err := os.WriteFile(filepath.Join(cfg, "user-dirs.dirs"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	l, err := NewLayout(home, cfg, noEnv)
	if err != nil {
		t.Fatal(err)
	}
	return home, l
}

// noEnv is an environment with nothing in it. Tests pass it so that a
// developer with XDG_DOCUMENTS_DIR exported cannot change a result.
func noEnv(string) string { return "" }

func mustRead(t *testing.T, p string) string {
	t.Helper()
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("reading %s: %v", p, err)
	}
	return string(b)
}
